#perform the tuple comprihension and get data using iter and next
my_tuple = (i for i in range(1, 50))
data=iter(my_tuple)
print(next(data))
print(next(data))
print(next(data))
print(next(data))
print(next(data))
print(next(data))
print(next(data))
print(next(data))
print(next(data))
print(next(data))
print(next(data))
